/**
 * This class is responsible for adding Author, Title and AuthorISBN
 */
package bookClientGui.GUI;

import bookClientGui.db.QueryData;
import bookClientGui.util.GUIUtil;
import java.awt.Rectangle;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author dheeraj
 */
public class AddDataJpanel extends javax.swing.JPanel {

    QueryData queryData;
    
    String tableNames [] ; // tableNames to show in jcombobox
    String [] searchAuthorByType ;
    String [] searchTitleByType ;
    String [] searchedAuthorDataResult ;
    String [] searchedTitleDataResult ;
    
    DefaultListModel searcheAuthorListModel = new DefaultListModel();
    DefaultListModel searcheTitleListModel = new DefaultListModel();
    
    Map<String, String> searchedTitleData;
    Map<String, String> searchedAuthorData;
    
    GUIUtil gUIUtil;
    
    /**
     * Creates new form AddDataJpanel
     */
    Rectangle bounds;
    public AddDataJpanel() {
        
        queryData = new QueryData();
        tableNames = queryData.getTableName();
        
        searchAuthorByType = new String[]{"FirstName","LastName"};
        searchTitleByType = new String[]{"ISBN","Title"};
        
        initComponents();
        
        addTitleJpanel.setVisible(false);
        addAuthorJpanel.setVisible(false);
        addAuthorISBNJpanel.setVisible(false);
        bounds = addTitleJpanel.getBounds();
        
        titleSuggestionJpanel.setVisible(false);
        authorSuggestionJpanel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxSelectTable = new javax.swing.JComboBox();
        addAuthorJpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        firstNameJtextfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lastNameJtextfield = new javax.swing.JTextField();
        addAuthorJbutton = new javax.swing.JButton();
        resetAuthorJbutton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        addTitleJpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        isbnJtextfield = new javax.swing.JTextField();
        titleJtextfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        editionNoJtextfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        copyrightJtextfield = new javax.swing.JTextField();
        addTitleJbutton = new javax.swing.JButton();
        resetTitleJbutton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        addAuthorISBNJpanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        searchAuthorByJtextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addAuthorISBNJbutton = new javax.swing.JButton();
        authorSuggestionJpanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        authorSuggestionJlist = new javax.swing.JList();
        searchTitleByJtextField = new javax.swing.JTextField();
        searchAuthorByJcomboBox = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        searchTitleByJcomboBox = new javax.swing.JComboBox();
        titleSuggestionJpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        titleSuggestionJlist = new javax.swing.JList();
        hiddenISBNJlable = new javax.swing.JLabel();
        hiddenAuthorIdJlable = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jComboBoxSelectTable.setModel(new javax.swing.DefaultComboBoxModel(tableNames));
        jComboBoxSelectTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectTableActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name: ");

        jLabel6.setText("Last Name: ");

        lastNameJtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameJtextfieldActionPerformed(evt);
            }
        });

        addAuthorJbutton.setText("Add");
        addAuthorJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAuthorJbuttonActionPerformed(evt);
            }
        });

        resetAuthorJbutton.setText("Reset");
        resetAuthorJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetAuthorJbuttonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Add Author");

        javax.swing.GroupLayout addAuthorJpanelLayout = new javax.swing.GroupLayout(addAuthorJpanel);
        addAuthorJpanel.setLayout(addAuthorJpanelLayout);
        addAuthorJpanelLayout.setHorizontalGroup(
            addAuthorJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAuthorJpanelLayout.createSequentialGroup()
                .addGroup(addAuthorJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addAuthorJpanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(addAuthorJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(addAuthorJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(addAuthorJpanelLayout.createSequentialGroup()
                                .addComponent(addAuthorJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetAuthorJbutton))
                            .addComponent(lastNameJtextfield)
                            .addComponent(firstNameJtextfield)))
                    .addGroup(addAuthorJpanelLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel10)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        addAuthorJpanelLayout.setVerticalGroup(
            addAuthorJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAuthorJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(40, 40, 40)
                .addGroup(addAuthorJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(firstNameJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addAuthorJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lastNameJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(addAuthorJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAuthorJbutton)
                    .addComponent(resetAuthorJbutton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("      ISBN: ");

        jLabel3.setText("      Title: ");

        titleJtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleJtextfieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Edition No.: ");

        jLabel5.setText("Copyright: ");

        addTitleJbutton.setText("Add");
        addTitleJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTitleJbuttonActionPerformed(evt);
            }
        });

        resetTitleJbutton.setText("Reset");
        resetTitleJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetTitleJbuttonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Add Title");

        javax.swing.GroupLayout addTitleJpanelLayout = new javax.swing.GroupLayout(addTitleJpanel);
        addTitleJpanel.setLayout(addTitleJpanelLayout);
        addTitleJpanelLayout.setHorizontalGroup(
            addTitleJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTitleJpanelLayout.createSequentialGroup()
                .addGroup(addTitleJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addTitleJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addTitleJpanelLayout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(jLabel5))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTitleJpanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addTitleJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addTitleJpanelLayout.createSequentialGroup()
                        .addComponent(addTitleJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetTitleJbutton))
                    .addComponent(isbnJtextfield)
                    .addComponent(titleJtextfield)
                    .addComponent(copyrightJtextfield)
                    .addComponent(editionNoJtextfield))
                .addGap(0, 48, Short.MAX_VALUE))
            .addGroup(addTitleJpanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addTitleJpanelLayout.setVerticalGroup(
            addTitleJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTitleJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(addTitleJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(isbnJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addTitleJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(titleJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(addTitleJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(editionNoJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addTitleJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(copyrightJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(addTitleJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTitleJbutton)
                    .addComponent(resetTitleJbutton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Search Author By:");

        searchAuthorByJtextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAuthorByJtextFieldActionPerformed(evt);
            }
        });
        searchAuthorByJtextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchAuthorByJtextFieldKeyReleased(evt);
            }
        });

        jLabel8.setText("Search Title By:");

        addAuthorISBNJbutton.setText("Add");
        addAuthorISBNJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAuthorISBNJbuttonActionPerformed(evt);
            }
        });

        authorSuggestionJlist.setModel(searcheAuthorListModel);
        authorSuggestionJlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                authorSuggestionJlistMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(authorSuggestionJlist);

        javax.swing.GroupLayout authorSuggestionJpanelLayout = new javax.swing.GroupLayout(authorSuggestionJpanel);
        authorSuggestionJpanel.setLayout(authorSuggestionJpanelLayout);
        authorSuggestionJpanelLayout.setHorizontalGroup(
            authorSuggestionJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        authorSuggestionJpanelLayout.setVerticalGroup(
            authorSuggestionJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authorSuggestionJpanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        searchTitleByJtextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTitleByJtextFieldActionPerformed(evt);
            }
        });
        searchTitleByJtextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTitleByJtextFieldKeyReleased(evt);
            }
        });

        searchAuthorByJcomboBox.setModel(new javax.swing.DefaultComboBoxModel(searchAuthorByType));
        searchAuthorByJcomboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAuthorByJcomboBoxActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Link Author with Title code");

        searchTitleByJcomboBox.setModel(new javax.swing.DefaultComboBoxModel(searchTitleByType));
        searchTitleByJcomboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTitleByJcomboBoxActionPerformed(evt);
            }
        });

        titleSuggestionJlist.setModel(searcheTitleListModel);
        titleSuggestionJlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleSuggestionJlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(titleSuggestionJlist);

        javax.swing.GroupLayout titleSuggestionJpanelLayout = new javax.swing.GroupLayout(titleSuggestionJpanel);
        titleSuggestionJpanel.setLayout(titleSuggestionJpanelLayout);
        titleSuggestionJpanelLayout.setHorizontalGroup(
            titleSuggestionJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        titleSuggestionJpanelLayout.setVerticalGroup(
            titleSuggestionJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleSuggestionJpanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addAuthorISBNJpanelLayout = new javax.swing.GroupLayout(addAuthorISBNJpanel);
        addAuthorISBNJpanel.setLayout(addAuthorISBNJpanelLayout);
        addAuthorISBNJpanelLayout.setHorizontalGroup(
            addAuthorISBNJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAuthorISBNJpanelLayout.createSequentialGroup()
                .addGroup(addAuthorISBNJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addAuthorISBNJpanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(addAuthorISBNJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addGroup(addAuthorISBNJpanelLayout.createSequentialGroup()
                                .addComponent(hiddenAuthorIdJlable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hiddenISBNJlable)))
                        .addGap(18, 18, 18)
                        .addGroup(addAuthorISBNJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchAuthorByJcomboBox, 0, 117, Short.MAX_VALUE)
                            .addComponent(addAuthorISBNJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchTitleByJcomboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(addAuthorISBNJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(titleSuggestionJpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchAuthorByJtextField, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(authorSuggestionJpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchTitleByJtextField)))
                    .addGroup(addAuthorISBNJpanelLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel11)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        addAuthorISBNJpanelLayout.setVerticalGroup(
            addAuthorISBNJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAuthorISBNJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(addAuthorISBNJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchAuthorByJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addAuthorISBNJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(searchAuthorByJcomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorSuggestionJpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(addAuthorISBNJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addAuthorISBNJpanelLayout.createSequentialGroup()
                        .addGroup(addAuthorISBNJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchTitleByJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchTitleByJcomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleSuggestionJpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addAuthorISBNJpanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8)
                        .addGap(32, 32, 32)
                        .addGroup(addAuthorISBNJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addAuthorISBNJbutton)
                            .addComponent(hiddenISBNJlable)
                            .addComponent(hiddenAuthorIdJlable))))
                .addContainerGap())
        );

        jLabel12.setText("Select Table: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxSelectTable, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addTitleJpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addAuthorJpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addAuthorISBNJpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addAuthorISBNJpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addAuthorJpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addTitleJpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSelectTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSelectTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectTableActionPerformed
        
        String selectedTable = (String)jComboBoxSelectTable.getSelectedItem();
        
        if(selectedTable.equals("Titles")){
            
            addTitleJpanel.setVisible(true);
            addAuthorJpanel.setVisible(false);
            addAuthorISBNJpanel.setVisible(false);
   
        }else if(selectedTable.equals("Authors")){
            
            addTitleJpanel.setVisible(false);
            addAuthorISBNJpanel.setVisible(false);
            addAuthorJpanel.setVisible(true);

        }else if (selectedTable.equals("AuthorISBN")){
            
            addTitleJpanel.setVisible(false);
            addAuthorJpanel.setVisible(false);
            addAuthorISBNJpanel.setVisible(true);
        }    
    }//GEN-LAST:event_jComboBoxSelectTableActionPerformed

    private void titleJtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleJtextfieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_titleJtextfieldActionPerformed

    private void lastNameJtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameJtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameJtextfieldActionPerformed

    private void searchTitleByJtextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTitleByJtextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTitleByJtextFieldActionPerformed

    /**
     * This method is responsible to add Title into the database 
     */
    private void addTitleJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTitleJbuttonActionPerformed
        
        try {
            String selectedTable = (String)jComboBoxSelectTable.getSelectedItem();
            
            String isbn = isbnJtextfield.getText();
            String title = titleJtextfield.getText();
            String editionNo = editionNoJtextfield.getText();
            String copyright = copyrightJtextfield.getText();
            
            if((isbn != null && isbn.equals("")) ||
                    (title != null && title.equals(""))||
                    (editionNo != null && editionNo.equals(""))||
                    (copyright != null && copyright.equals(""))){
                
                new GUIUtil().showWarningDialoge("Warning", "All the fields are mandatory", this);
                
            }else{
                int i = queryData.addTitle(selectedTable, Integer.parseInt(isbn), title, Integer.parseInt(editionNo), Integer.parseInt(copyright));
                if( i != 0){
                    
                    resetTitleField();
                    new GUIUtil().showPlainDialog("Title has been added successfully", this);
                }
            } 
        
        } catch (NumberFormatException e) {
            
            JOptionPane.showMessageDialog(this,
                "ISBN / Eidiotn No / Copyright should be numeric only",
                "Invalid value",
                JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_addTitleJbuttonActionPerformed

    /**
     * This method is responsible to reset the fields of add Title form 
     */
    private void resetTitleField(){
        
        isbnJtextfield.setText("");
        titleJtextfield.setText("");
        copyrightJtextfield.setText("");
        editionNoJtextfield.setText("");
    }
      
    /**
     * This method is responsible to reset the fields of add Author form 
     */
    private void resetAuthorField(){
        
        firstNameJtextfield.setText("");
        lastNameJtextfield.setText("");
    }
    
    private void addAuthorJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAuthorJbuttonActionPerformed
       
        String selectedTable = (String)jComboBoxSelectTable.getSelectedItem();
        String firstName = firstNameJtextfield.getText();
        String lastName = lastNameJtextfield.getText();
        
        if((firstName != null && firstName.equals(""))
                || (lastName != null && lastName.equals("") )){
            new GUIUtil().showWarningDialoge("Warning", "First Name / Last Name can not be blank", this);
        }else{
            int i = queryData.addAuthor(selectedTable, firstName, lastName);
            if(i != 0){
                resetAuthorField();
                new GUIUtil().showPlainDialog("Author has been added successfully", this);
            }
        } 
    }//GEN-LAST:event_addAuthorJbuttonActionPerformed

    private void resetTitleJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetTitleJbuttonActionPerformed
        resetTitleField();
    }//GEN-LAST:event_resetTitleJbuttonActionPerformed

    private void resetAuthorJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetAuthorJbuttonActionPerformed
        resetAuthorField();
    }//GEN-LAST:event_resetAuthorJbuttonActionPerformed

    private void searchAuthorByJtextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAuthorByJtextFieldActionPerformed

    }//GEN-LAST:event_searchAuthorByJtextFieldActionPerformed

    private void searchAuthorByJtextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchAuthorByJtextFieldKeyReleased

        if(searchAuthorByJtextField.getText() != null && searchAuthorByJtextField.getText().length() > 0){
            
            String searchAuthorBy = (String)searchAuthorByJcomboBox.getSelectedItem();
        String searchByValue =  searchAuthorByJtextField.getText();
        
        searchedAuthorData = queryData.searchData("Authors", searchAuthorBy, searchByValue);
        searchedAuthorDataResult = new String[searchedAuthorData.size()];
        
        searcheAuthorListModel.removeAllElements();
        for (String key : searchedAuthorData.keySet()) {
            
            searcheAuthorListModel.addElement(searchedAuthorData.get(key) + ">ID"+key);
        }
        if(searchedAuthorData.size() > 0){
            authorSuggestionJpanel.setVisible(true);
        }else{
            authorSuggestionJpanel.setVisible(false);
        }
        }
    }//GEN-LAST:event_searchAuthorByJtextFieldKeyReleased

    private void addAuthorISBNJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAuthorISBNJbuttonActionPerformed
        
        String searchByAuthorValue = (String)searchAuthorByJtextField.getText();
        String searchByTitleValue = (String)searchTitleByJtextField.getText();
        
        if((searchByAuthorValue != null && searchByAuthorValue.equals("")) || (searchByTitleValue != null && searchByTitleValue.equals("") )){
            new GUIUtil().showWarningDialoge("Warning", "All fields are mandatory", this);
            
        }else{
            if(searchByAuthorValue != null && searchByAuthorValue.contains(">ID")){
                String searchByTitle [] = searchByAuthorValue.split(">ID");
                searchByAuthorValue = searchByTitle[1];
            }
        
            if(searchByTitleValue != null && searchByTitleValue.contains(">ISBN")){
                String searchByTitle [] = searchByTitleValue.split(">ISBN");
                searchByTitleValue = searchByTitle[1];
            }
            queryData.addAuthorISBN(searchByAuthorValue, searchByTitleValue);
            searchAuthorByJtextField.setText("");
            searchTitleByJtextField.setText("");
            new GUIUtil().showPlainDialog("Author and Title are linked successfully!", this);      
        }
        
    }//GEN-LAST:event_addAuthorISBNJbuttonActionPerformed

    private void searchAuthorByJcomboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAuthorByJcomboBoxActionPerformed
        
        searchAuthorByJtextField.setText("");
        searcheAuthorListModel.removeAllElements();
        authorSuggestionJpanel.setVisible(false);
    }//GEN-LAST:event_searchAuthorByJcomboBoxActionPerformed

    private void authorSuggestionJlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_authorSuggestionJlistMouseClicked
        
        if (evt.getClickCount() == 2) {
            hiddenAuthorIdJlable.setText(searchedAuthorData.get(searchAuthorByJtextField.getText()));
            searchAuthorByJtextField.setText((String)authorSuggestionJlist.getSelectedValue());
            searcheAuthorListModel.removeAllElements();
            authorSuggestionJpanel.setVisible(false);
        }
    }//GEN-LAST:event_authorSuggestionJlistMouseClicked

    private void searchTitleByJcomboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTitleByJcomboBoxActionPerformed
        
        searchTitleByJtextField.setText("");
        searcheTitleListModel.removeAllElements();
        titleSuggestionJpanel.setVisible(false);
    }//GEN-LAST:event_searchTitleByJcomboBoxActionPerformed

    private void searchTitleByJtextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTitleByJtextFieldKeyReleased

        if(searchTitleByJtextField.getText() != null && searchTitleByJtextField.getText().length() > 0){
            
        String searchTitleBy = (String)searchTitleByJcomboBox.getSelectedItem();
        String searchByValue =  searchTitleByJtextField.getText();
        
        searchedTitleData = queryData.searchData("Titles", searchTitleBy, searchByValue);
    
        searchedTitleDataResult = new String[searchedTitleData.size()];
        
        searcheTitleListModel.removeAllElements();

        for (String key : searchedTitleData.keySet()) {
            if(searchTitleBy.equals("ISBN")){
                searcheTitleListModel.addElement(searchedTitleData.get(key));
            }else{
                searcheTitleListModel.addElement(searchedTitleData.get(key) +">ISBN"+key);
            }  
        }
        if(searchedTitleData.size() > 0){
            titleSuggestionJpanel.setVisible(true);
        }else{
            titleSuggestionJpanel.setVisible(false);
        }
        } 
    }//GEN-LAST:event_searchTitleByJtextFieldKeyReleased

    private void titleSuggestionJlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleSuggestionJlistMouseClicked
        
        if (evt.getClickCount() == 2) {
            searchTitleByJtextField.setText((String)titleSuggestionJlist.getSelectedValue());
            searcheTitleListModel.removeAllElements();
            titleSuggestionJpanel.setVisible(false);
        }
    }//GEN-LAST:event_titleSuggestionJlistMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAuthorISBNJbutton;
    private javax.swing.JPanel addAuthorISBNJpanel;
    private javax.swing.JButton addAuthorJbutton;
    private javax.swing.JPanel addAuthorJpanel;
    private javax.swing.JButton addTitleJbutton;
    private javax.swing.JPanel addTitleJpanel;
    private javax.swing.JList authorSuggestionJlist;
    private javax.swing.JPanel authorSuggestionJpanel;
    private javax.swing.JTextField copyrightJtextfield;
    private javax.swing.JTextField editionNoJtextfield;
    private javax.swing.JTextField firstNameJtextfield;
    private javax.swing.JLabel hiddenAuthorIdJlable;
    private javax.swing.JLabel hiddenISBNJlable;
    private javax.swing.JTextField isbnJtextfield;
    private javax.swing.JComboBox jComboBoxSelectTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastNameJtextfield;
    private javax.swing.JButton resetAuthorJbutton;
    private javax.swing.JButton resetTitleJbutton;
    private javax.swing.JComboBox searchAuthorByJcomboBox;
    private javax.swing.JTextField searchAuthorByJtextField;
    private javax.swing.JComboBox searchTitleByJcomboBox;
    private javax.swing.JTextField searchTitleByJtextField;
    private javax.swing.JTextField titleJtextfield;
    private javax.swing.JList titleSuggestionJlist;
    private javax.swing.JPanel titleSuggestionJpanel;
    // End of variables declaration//GEN-END:variables
}
