/*
 *This class is responsible for login activity of user
 */
package bookClientGui.GUI;

import bookClientGui.db.EstablishConnection;
import java.awt.Component;
import java.awt.Container;
import javax.swing.JButton;
import javax.swing.JTabbedPane;

/**
 *
 * @author dheeraj
 */
public class LoginFormJpanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginFormJpanel
     */
    public LoginFormJpanel() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameJtextField = new javax.swing.JTextField();
        paswordJtextField = new javax.swing.JPasswordField();
        submitButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        errorJlabel = new javax.swing.JLabel();

        jLabel1.setText("User Name: ");

        jLabel2.setText("Password:");

        userNameJtextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameJtextFieldActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        errorLabel.setText(" ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Login Here");

        errorJlabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        errorJlabel.setText("   ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(errorJlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(submitButton)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(userNameJtextField)
                        .addComponent(paswordJtextField)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(errorLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)))
                .addGap(15, 15, 15)
                .addComponent(errorJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userNameJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(paswordJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(submitButton)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userNameJtextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameJtextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameJtextFieldActionPerformed

    /**
     * This method checks the user credentials with the data base and respond accordingly 
    */
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        
        String userName = userNameJtextField.getText();
        char [] password = paswordJtextField.getPassword();
        
        if(userName != null && userName.equals("")){
            errorJlabel.setText("User Name/Password can't be blank");
        }else{
            EstablishConnection establishConnection = new EstablishConnection();
            if(establishConnection.createDBConnection(userName, String.valueOf(password)) == null){
                errorJlabel.setText("User Name/Password Invalid");
            }else{
                
                userNameJtextField.setText("");
                paswordJtextField.setText("");
                JButton button = (JButton) evt.getSource();
                Container container = button.getParent();
                container.setVisible(false);
                Component [] parentComponents = container.getParent().getComponents();
                for (Component parentComponent : parentComponents) {
                    if(parentComponent.getName() != null && parentComponent.getName().equals("mainJtabbedPane")){
                        
                        // Add maintain Data Tabbed Pane to the Main Frame
                        MaintainDataJpanel maintainDataJpanel = new MaintainDataJpanel();
                        maintainDataJpanel.setName("maintainDataJpanel");
                        ((JTabbedPane)parentComponent).addTab("Maintain Data", maintainDataJpanel);
                        
                        // Add Add data Data Tabbed Pane to the Main Frame
                        AddDataJpanel addDataJpanel = new AddDataJpanel();
                        addDataJpanel.setName("addDataJpanel");
                        ((JTabbedPane)parentComponent).addTab("Add Data", addDataJpanel);
                        
                        // Add Retrieve Data Tabbed Pane to the Main Frame
                        RetrieveDataJpanel retrieveDataJpanel = new RetrieveDataJpanel();
                        addDataJpanel.setName("retrieveDataJpanel");
                        ((JTabbedPane)parentComponent).addTab("Retrieve Data", retrieveDataJpanel);
                        
                        parentComponent.setVisible(true);
                        parentComponent.setSize(1200, 800);
                    }else if(parentComponent.getName() != null && parentComponent.getName().equals("logOutJbutton")){
                        parentComponent.setVisible(true);
                    }else if(parentComponent.getName() != null && parentComponent.getName().equals("welcomeJlabel")){
                        parentComponent.setVisible(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorJlabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField paswordJtextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField userNameJtextField;
    // End of variables declaration//GEN-END:variables
}
